config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tweets  do
    resources :likes, only: [:create, :destroy]
  end
  root 'tweets#top'
  get 'tweets/new' => 'tweets#new'
  get 'tweets/show' => 'tweets#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  acts_as_taggable_on :tags
  belongs_to :user 
  mount_uploader :photo, ImageUploader
  has_one_attached :image

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy#追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  validates :name, presence: true, length:{ maximum: 50} #追記
  validates :profile, length: { maximum: 200 } #追記       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def top
  end
  def index
    @tweets = Tweet.all.order(created_at: :desc)
    @tweet = Tweet.new

    if params[:search] != nil && params[:search] != ''
      #部分検索かつ複数検索
      search = params[:search]
      @tweets = Tweet.joins(:user).where("comment LIKE ? OR cocktail LIKE ?", "%#{search}%", "%#{search}%")
    end
   
    if params[:tag_name]
      @tweets = Tweet.tagged_with("#{params[:tag_name]}")
    end

  end

  def show
  end
  
  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id 
    if tweet.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "index", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:cocktail, :image, :Base, :comment, :tag_list, :created_at)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    @users = User.all.order(created_at: :desc)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktailapplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/55ec9495de.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#>= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg_test">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <header>
      <div class="見出し0">
        <div class="見出し2">
          Sip & Love
        </div>
        <div class="見出し">
          Sip & Love
        </div>
      </div>

        
        
        
        <div class="見出し3">
          <%= link_to "Home", tweets_path  %></li>
        </div>
            


        <div class="登録">
          <% if user_signed_in? %>
            
            <%= link_to 'My page', user_path(current_user.id) %></li>
          <% else %>
          
          <%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </div>

        <div class="hamburger-menu">
          <input type="checkbox" id="menu-btn-check">
          <label for="menu-btn-check" class="menu-btn"><span></span></label>
        
      

        <div class="menu-content">
          <ul>
            <li><%= link_to "Top", root_path  %></li>
            
            <li><%= link_to "About", tweets_show_path %></li>

            <li><%= link_to "New Post", tweets_new_path %></li>
          </ul>
      </div>

    </div>

    </header>
      <%= yield %>

    <footer>
      <div class="footer-list">
        <div class="last">
          Sip&Love
        </div>

        <div class="last2">
          オシャレな時間になれていれば幸いです
        </div>
      </div>
    </footer>
  </body>

</html>

app/views/tweets/_tag_list.html.erb
<% tag_list.each do |tag|%>
  <div class="btn btn-primary">
    <%= link_to tag, tweets_path(tag_name: tag) %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :キャプション %>
  <%= f.text_field :comment, :size => "30x2" %>

<p><div class="tag_edit"></p>
  <%= f.label :タグ %>
  <%= f.text_field :tag_list, value: @tweet.tag_list %>  
  </div>

  <p><%= f.submit "完了" %></p>
<% end %>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag "index", :media => "all" %>
    <h1>みんなのCocktails</h1>
    <h3>Cocktails一覧</h3>
    <%= link_to "New Cocktai POSTへ", new_tweet_path %>
    <br>
    <br>
    <p><h3>Cocktailを探す</h3></p>
    <div class="けんさく">
    <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索する'  %>
    </div>


    <% end %>


    <div class="tweets-container">
        <% @tweets.each do |t| %>
        <div class="tweet">
                <%= t.user.name %>
                <% if t.image.attached? %>
                    <p><%= image_tag t.image, class: '一覧画像'%></p>
                <% end %>
                <div class="一覧カクテル名">
                <p><%= t.cocktail %></p>
                </div>
                <p><%= t.Base %></p>
                <p><%= t.comment %></p>
                <%= render 'tweets/tag_list', tag_list: t.tag_list %>
                
                <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                    <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                        <i class="fa-regular fa-heart"></i><%= t.likes.count %>
                    <% end %>
                <% else %>
                    <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                        <i class="fa-regular fa-heart"></i><%= t.likes.count %>
                    <% end %>
                <% end %>
                <% else %>
                    <i class="fa-regular fa-heart"></i><%= t.likes.count %>
                <% end %>

                <p><%= t.created_at.to_s(:datetime_jp) %></p>        
                <% if user_signed_in? && current_user.id == t.user_id %>
                    <%= link_to "編集する", edit_tweet_path(t.id) %>
                    <%= button_to "削除する", tweet_path(t.id), method: :delete %>
                <% end %>
        </div>
        <% end %>
    </div>    

app/views/tweets/new.html.erb
<%= stylesheet_link_tag "new", :media => "all" %>
<h1>New Cocktail POST</h1>
<h3>新規Cocktail投稿</h3>
<%= form_for @tweet do |f| %>

<div class="新規投稿">

        <div class="fieldA">
            <div class ="post1">
            <%= f.label :写真を選択 %>
            </div>
            <div class ="post2">
            <%= f.file_field :image %>
            </div>
        </div>    </>
        
        <p><div class="fieldB"></p>
            <div class ="post3">
            <%= f.label :Cocktail_Name %>
            </div>
            <div class ="post4">
            <%= f.text_field :cocktail, :size => 50 %>
            </div>
        </div>

        <p><div class="fieldC"></p>
            <div class ="post5">
            <%= f.label :ベースとなるお酒 %>
            </div>
            <div class ="post6">
            <%= f.text_field :Base, :size => 50 %>
            </div>
        </div>

        <p><div class="fieldD"></p>
            <div class ="post7">
            <%= f.label :キャプションを入力  %>
            </div>
            <div class ="post8">
            <%= f.text_area :comment, :size => "50x2" %>
            </div>
        </div>

        <p><div class="fieldE"></p>
            <div class ="post9">
            <%= f.label :タグ %>(半角スペースを使って複数付けてみましょう)
            </div>
            <div class ="post10">
            <%= f.text_field :tag_list, value: @tweet.tag_list, :size=>50 %>
            </div>
        </div>
</div>

<p></p><div class="fieldF"></p>
    <%= f.submit "シェアする",:size =>"50px" %>
</div>
<% end %>

app/views/tweets/show.html.erb
<%= stylesheet_link_tag "show", :media => "all" %>
<div class="Container">
    <div class="Item">

    </div>

    
    <div class="Item2">
        <div class="contents1">
            <div class="Text1">
                <h2>-From  Sip&Love -</h2>

                <div class="scroll1">
                お酒が好きな人も、嫌いな人も、
                大人数で楽しみたい人も、1人でしっぽり楽しみたい人もいると思います。<br><br>
                たくさんあるお酒の中でカクテルって特にオシャレだと思いませんか？<br><br>
                しかし、カクテルの種類は本当に多く、BARに行っても同じようなものばかり注文することありませんか？
                カクテルについて詳しくないからBARには抵抗がある方はいませんか？

                <br>
                <br>
                味、匂い、色で楽しめるカクテルをたくさん知りたいと思う方に向けて作成しました。
                Sip&Loveでオシャレな知識を増やしましょう。
                
                </div>
            </div>
        </div>


        <div class="contents2">
            <div class="Text2">
                    <div class="scroll2">
                        <h2>01.</h2>
                        <h2>Enjoy Watching</h2>
                        <h3>みんなのCocktails一覧でカクテル投稿を確認</h3>

                            <div class="本文2">
                                皆様が投稿しているカクテルを流し見することで気になるカクテルに出会うかもしれません。
                                飲んでみたい、オシャレと思った投稿にはいいねを押してみるのも押してみるのもよいでしょう。
                            </div>
                    </div>

                <br>
                <br>
                <br>
                <div class="scroll3">
                    <h2>02.</h2>
                    <h2>Post</h2>
                    <h3>自分自身が飲んでみたカクテルを投稿しましょう</h3>

                        <div class="本文2">
                            カクテルの名前、写真、ベースのお酒、一言、そしてタグをつけて投稿してみてください。
                            タグを多くつけると検索されやすくなります。
                        </div>
                </div>

                <br>
                <br>
                <br>
                <div class="scroll4">
                    <h2>03.</h2>
                    <h2>Search</h2>
                    <h3>カクテルの名前やタグで検索してみましょう</h3>

                        <div class="本文2">
                            どのようなカクテルか調べたい際、BARに行った際にメニューに書いてカクテルなど
                            名前で検索してみましょう。
                            <p>また、甘い、トロピカル、スッキリなど単語で調べたい時でもタグ機能があることで
                            名前を知らなくても検索できます。</p>
                        </div>
                </div>
                
            </div>
        </div>

    </div>

</div>

app/views/tweets/top.html.erb
<!DOCTYPE html> 
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
<body>
<%= stylesheet_link_tag "top", :media => "all" %>
<main>   
<div class="slider">
  <!-- slides -->
  <div class="slider__slides">
    <div class="slide s--active">
      <div class="slide__inner">
        <div class="slide__content">
          <h2 class="slide__heading">Welcome to the colorful world!</h2>
          <p class="slide__text">Greetings, everyone!</p>
        </div>
      </div>
    </div>
    <div class="slide">
      <div class="slide__inner">
        <div class="slide__content">
          <h2 class="slide__heading">Stylish Space</h2>
          <p class="slide__text">Take up a new hobby</p>
        </div>
      </div>
    </div>
    <div class="slide">
      <div class="slide__inner">
        <div class="slide__content">
          <h2 class="slide__heading">Enjoy with color</h2>
          <p class="slide__text">It's like fireworks</p>
        </div>
      </div>
    </div>
    <div class="slide">
      <div class="slide__inner">
        <div class="slide__content">
          <h2 class="slide__heading">Cocktails aren't just about taste!</h2>
          <p class="slide__text">Also uses salt, fruits, and flowers.</p>
        </div>
      </div>
    </div>
    <div class="slide s--prev">
      <div class="slide__inner">
        <div class="slide__content">
          <h2 class="slide__heading">It's truly an art.</h2>
          <p class="slide__text">Let's make a wonderful time.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- slides end -->
  <div class="slider__control">
    <div class="slider__control-line"></div>
    <div class="slider__control-line"></div>
  </div>
  <div class="slider__control slider__control--right m--right">
    <div class="slider__control-line"></div>
    <div class="slider__control-line"></div>
  </div>
</div>
</main>

<script>
    (function() {
    var $slides = document.querySelectorAll('.slide');
    var $controls = document.querySelectorAll('.slider__control');
    var numOfSlides = $slides.length;
    var slidingAT = 1300; // sync this with scss variable
    var slidingBlocked = false;
  
    [].slice.call($slides).forEach(function($el, index) {
      var i = index + 1;
      $el.classList.add('slide-' + i);
      $el.dataset.slide = i;
    });
  
    [].slice.call($controls).forEach(function($el) {
      $el.addEventListener('click', controlClickHandler);
    });
  
    function controlClickHandler() {
      if (slidingBlocked) return;
      slidingBlocked = true;
  
      var $control = this;
      var isRight = $control.classList.contains('m--right');
      var $curActive = document.querySelector('.slide.s--active');
      var index = +$curActive.dataset.slide;
      (isRight) ? index++ : index--;
      if (index < 1) index = numOfSlides;
      if (index > numOfSlides) index = 1;
      var $newActive = document.querySelector('.slide-' + index);
  
      $control.classList.add('a--rotation');
      $curActive.classList.remove('s--active', 's--active-prev');
      document.querySelector('.slide.s--prev').classList.remove('s--prev');
      
      $newActive.classList.add('s--active');
      if (!isRight) $newActive.classList.add('s--active-prev');
      
  
      var prevIndex = index - 1;
      if (prevIndex < 1) prevIndex = numOfSlides;
  
      document.querySelector('.slide-' + prevIndex).classList.add('s--prev');
  
      setTimeout(function() {
        $control.classList.remove('a--rotation');
        slidingBlocked = false;
      }, slidingAT*0.75);
    };
  }());
</script>


<div id="container">
  <div class="item1">
      <div class="box1">
          <div class="text1">
          カクテルとは…
          </div>
      </div>
      <div class="box2">
        <%= image_tag "about3.jpg", size: '100x200', class: 'osake1' %>
      </div>
  </div>


  <div class="item2">
      <div class="box3">
        <%= image_tag "about2.jpg" , class: 'osake2'%>
      </div>

      <div class="box4">
        <%= image_tag "about1.jpg" , class: 'osake3'%>
      </div>

      <div class="box5">
        <div class="text2">
          ベースとなるお酒に複数の別のお酒や果汁、シロップなどを加え、
          <p>混ぜて作るドリンクです。</p>
        </div>
      </div>

      <div class="box6">
        <%= image_tag "about7.jpg" , class: 'osake4'%>
      </div>
  </div>

  <div class="item3">
      <div class="box7">
        <div class="text3">
          カクテルの歴史は諸説あるが、古代ローマ、古代ギリシャ、古代エジプトの時代まで遡ります。
        </div>
      </div>

      <div class="box8">
        <%= image_tag "about8.jpg" ,  class: 'osake5'%>
      </div>

      <div class="box9">
        <div class="text3a">
          当時ワインやビールがあったが、品質が落ちるのを防ぐ、また劣化・酸化を防ぐために「何かを混ぜて飲んでいた」のがカクテルのスタートと言われています。
        </div>
      </div>
  </div>


  <div class="item4">
      <div class="box10">
        <%= image_tag "about4.jpeg" ,  class: 'osake6'%>
      </div>

      <div class="box11">
        <div class="text4">
          世界1古いカクテルは「サゼラック」と言われています。
          ウイスキー、アブサン、ビダーズ、砂糖をブレンドしたものです。
        </div>
      </div>

      <div class="box12">
        <%= image_tag "about10.jpg" ,  class: 'osake7'%>
      </div>
  </div>


  <div class="item5">
      <div class="box13">
        <%= image_tag "about6.jpg" ,  class: 'osake8'%>
      </div>

      <div class="box14">
        <%= image_tag "about5.jpg" ,  class: 'osake9'%>
      </div>

      <div class="box15">
        <div class="text5">
          また、カクテルの最高度数は「スピリタス」という世界最高のアルコール度数96度が有名です…知らずに飲むと危ないですよね
        </div>
      </div>
  </div>

  </div>
  <div class="item6">
    <div class="text6">
      自分のお気に入りをここで見つけてみてください。
    </div>
  </div>


  <div id="container2">
    <div class= "item7">
      <div class= "text7">
        ベースとなるお酒
      </div>
    </div>

    <div class= "item7A">
      画像をクリックして見てみましょう
    </div>

    <div class="baseosake1">
      <div class= "item8">
        <div class="box16">
          <div class= "text8">
              ジン-Gin
          </div>
        </div>

          <div class="box17">
            <%= link_to "http://www.cocktailtype.com/sp/cocktail/cocktail_base_0004.html" do %>
            <%= image_tag 'base1.jpg', width: 300, height: 300, crop: "fill", quality: "auto", fetch_format: "auto", class:"baseA" %>
            <% end %>
          </div>
      </div>

      <div class= "item9">
        <div class="box18">
          <div class= "text9">
              ウォッカ-Vodka
          </div>
        </div>

          <div class="box19">
            <%= link_to "http://www.cocktailtype.com/sp/cocktail/cocktail_base_0002.html" do %>
            <%= image_tag 'base2.jpg', width: 300, height: 300, crop: "fill", quality: "auto", fetch_format: "auto", class:"baseB" %>
            <% end %>
          </div>
      </div>

      <div class= "item10">
        <div class="box20">
          <div class= "text10">
              テキーラ-Tequila
          </div>
        </div>

          <div class="box21">
            <%= link_to "http://www.cocktailtype.com/sp/cocktail/cocktail_base_0006.html" do %>
            <%= image_tag 'base3.jpg', width: 300, height: 300, crop: "fill", quality: "auto", fetch_format: "auto", class:"baseC" %>
            <% end %>
          </div>
      </div>

    </div>

    <div class="baseosake2">
      <div class= "item11">
          <div class="box22">
            <div class= "text11">
              ラム-Rum
          </div>
        </div>

        <div class="box23">
            <%= link_to "http://www.cocktailtype.com/sp/cocktail/cocktail_base_0009.html" do %>
            <%= image_tag 'base4.jpg', width: 300, height: 300, crop: "fill", quality: "auto", fetch_format: "auto", class:"baseD" %>
            <% end %>
        </div>
      </div>


      <div class= "item12">
          <div class="box24">
            <div class= "text12">
              ウイスキー-Whiskey
          </div>
        </div>

        <div class="box25">
            <%= link_to "http://www.cocktailtype.com/sp/cocktail/cocktail_base_0001.html" do %>
            <%= image_tag 'base5.jpg', width: 300, height: 300, crop: "fill", quality: "auto", fetch_format: "auto", class:"baseE" %>
            <% end %>
        </div>
      </div>


      <div class= "item13">
          <div class="box26">
            <div class= "text13">
                ブランデー-Brandy
          </div>
        </div>

        <div class="box27">
            <%= link_to "http://www.cocktailtype.com/sp/cocktail/cocktail_base_0008.html" do %>
            <%= image_tag 'base6.jpg', width: 300, height: 300, crop: "fill", quality: "auto", fetch_format: "auto", class:"baseF" %>
            <% end %>
        </div>
      </div>
    </div>

  
    <div class="baseosake3">
      <div class= "item14">
          <div class="box28">
            <div class= "text14">
              リキュール-Liqueur
          </div>
        </div>

        <div class="box29">
            <%= link_to "http://www.cocktailtype.com/sp/cocktail/cocktail_base_0010.html" do %>
            <%= image_tag 'base7.jpg', width: 300, height: 300, crop: "fill", quality: "auto", fetch_format: "auto", class:"baseG" %>
            <% end %>
        </div>
      </div>


      <div class= "item15">
          <div class="box30">
            <div class= "text15">
              シャンパン-Champagne
          </div>
        </div>

        <div class="box31">
            <%= link_to "http://www.cocktailtype.com/sp/cocktail/cocktail_base_0003.html" do %>
            <%= image_tag 'base8.jpg', width: 300, height: 300, crop: "fill", quality: "auto", fetch_format: "auto", class:"baseH" %>
            <% end %>
        </div>
      </div>


      <div class= "item16">
          <div class="box32">
            <div class= "text16">
                ワイン-Wine
          </div>
        </div>

        <div class="box33">
            <%= link_to "http://www.cocktailtype.com/sp/cocktail/cocktail_base_0011.html" do %>
            <%= image_tag 'base9.jpg', width: 300, height: 300, crop: "fill", quality: "auto", fetch_format: "auto", class:"baseI" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>


</body>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Name : <%= @user.name %></h1>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<div class="tweets-container">
   <% @user.tweets.each do |t| %>
    <div class="tweet">
    <p><%= t.user.name %></p>
    <% if t.image.attached? %>
      <p><%= image_tag t.image, class: '一覧画像'%></p>
    <% end %>
    <div class="一覧カクテル名">
    <p><%= t.cocktail %></p>
    </div>
    <p><%= t.Base %></p>
    <p><%= t.comment %></p>
    <%= render 'tweets/tag_list', tag_list: t.tag_list %>
    
    <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                <i class="fa-regular fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% else %>
            <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                <i class="fa-regular fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% end %>
      <% else %>
          <i class="fa-regular fa-heart"></i> <%= t.likes.count %>
      <% end %>

      <%= t.created_at.to_s(:datetime_jp) %>
      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete %> 
    <% end %>
    </div>
  <% end %>
</div>


<p><%= link_to "みんなのCocktails一覧へ", tweets_path %></p>